coverage:
  precision: 2
  round: nearest
  range: "90...95"
  status:
    project:
      default: off
      tests:
        target: 90%
        paths: "tests"
      app:
        target: 95%
        paths: "app"
    patch:
      default: off
      tests:
        target: 95%
        paths: "tests"
      app:
        target: 98%
        paths: "app"
  ignore:
    - "**/thirdparty/.*"
    - "**/test_build/.*"

flags:
  app:
    paths:
      - "app/"
  tests:
    paths:
      - "tests/"

codecov:
  branch: master

comment:
  layout: "reach, diff, flags, files"
